version: 2
updates:
- package-ecosystem: "pip" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  # Workflow files stored in the default location of `.github/workflows`
  # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
  directory: "/"
  schedule:
    interval: "daily"