exclude: 'node_modules|.git'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "leave_calendar.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-yaml
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'  # Use the sha / tag you want to point at
    hooks:
    - id: prettier
      types_or: [css, javascript]

  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: 'v1.0.5'  # Use the sha / tag you want to point at
    hooks:
    -   id: csslint
    
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.20.1'  # Use the sha / tag you want to point at
    hooks:
    - id: eslint
      additional_dependencies:
      - eslint@9.20.1
      - eslint-config-prettier@9.1.0
      - globals
      - "@eslint/js"

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.21.0
    hooks:
        - id: commitlint
          stages: [commit-msg]
          additional_dependencies: ['@commitlint/config-conventional']