name: pre-commit

on:
  pull_request:

concurrency:
  group: precommit-leave_calendar-${{ github.event_name }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  linter:
    name: 'precommit'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - uses: pre-commit/action@v3.0.1